stages: 
  - rust_build
  - docker_build

build: 
  stage: rust_build
  image: rust:bookworm
  script: 
    - cargo build --release
  artifacts: 
    paths: 
      - target/release/stenograph_api
    expire_in: 12 hours
